package com.wutsi.application.cash.endpoint

object Page {
    const val CASHIN = "page.cashin"
    const val CASHIN_CONFIRM = "page.cashin.confirm"
    const val CASHIN_SUCCESS = "page.cashin.success"
    const val CASHIN_ERROR = "page.cashin.error"
    const val CASHIN_PENDING = "page.cashin.pending"
    const val CASHIN_PIN = "page.cashin.pin"
    const val CASHOUT = "page.cashout"
    const val CASHOUT_SUCCESS = "page.cashout.success"
    const val CASHOUT_ERROR = "page.cashout.error"
    const val CASHOUT_PENDING = "page.cashout.pending"
    const val CASHOUT_PIN = "page.cashout.pin"
    const val SEND = "page.send"
    const val SEND_APPROVAL = "page.send.approval"
    const val SEND_RECIPIENT = "page.send.recipient"
    const val SEND_RECIPIENT_NOT_FOUND = "page.send.recipient.not-found"
    const val SEND_CONFIRM = "page.send.confirm"
    const val SEND_PENDING = "page.send.pending"
    const val SEND_PIN = "page.send.pin"
    const val SEND_SUCCESS = "page.send.success"
    const val SEND_ERROR = "page.send.error"
    const val HISTORY = "page.history"
    const val TRANSACTION = "page.transaction"
    const val PAY = "page.pay"
    const val PAY_QR_CODE = "page.pay.qr-code"
    const val PAY_SUCCESS = "page.pay.success"
    const val PAY_ERROR = "page.pay.error"
    const val PAY_CONFIRM = "page.pay.confirm"
    const val PAY_PIN = "page.pay.pin"
}
